/**
 * @fileoverview Vault Core — deterministic password generation & BIP39 utilities
 *
 * This module is the cryptographic heart of Vault. It is shared between:
 *   - popup/popup.js  (UI layer)
 *   - background.js   (service worker, via future message handlers)
 *
 * All functions are pure or use only the Web Crypto API — no network calls,
 * no storage reads. This makes the module easy to test and audit in isolation.
 *
 * Password generation algorithm (compatible with the web version):
 *   ```
 *   privateKey = BigInt(wordIndices).toString(16)
 *   password = "PASS" + SHA256(privateKey + "/" + user + "/" + site + "/" + nonce)
 *                           .substring(0, hashLength)
 *              + "249+"
 *   ```
 *
 * BIP39 reference: https://github.com/trezor/python-mnemonic/blob/master/src/mnemonic/wordlist/english.txt
 * `words` is the global BIP39 wordlist injected by lib/bip39WordList.js.
 *
 * @module VaultCore
 */

const VaultCore = (() => {

  // ─────────────────────────────────────────────────────────────────────────
  // Internal helpers
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Convert a decimal string (potentially very large) to a hexadecimal string.
   *
   * Used to turn a concatenated word-index string (e.g. "00020048...") into the
   * hex private key. JavaScript's `BigInt` handles arbitrarily large integers,
   * which is necessary because a 24-word phrase produces a ~88-digit decimal.
   *
   * @param  {string} decStr - A non-negative decimal integer as a string.
   * @returns {string} The hexadecimal representation (no "0x" prefix).
   * @throws {Error} If `decStr` contains non-digit characters.
   *
   * @example
   * decimalStringToHex("255") // → "ff"
   * decimalStringToHex("65535") // → "ffff"
   */
  function decimalStringToHex(decStr) {
    if (!/^\d+$/.test(decStr)) throw new Error('Invalid decimal string');
    return BigInt(decStr).toString(16);
  }

  /**
   * Convert a space-separated BIP39 seed phrase to a zero-padded index string.
   *
   * Each word maps to its 0-based index in the 2048-word BIP39 wordlist.
   * Each index is left-padded to 4 decimal digits (e.g., word at index 42 → "0042").
   * The resulting string is then converted to hex by `decimalStringToHex`.
   *
   * Example for a 3-word phrase "abandon about actual":
   *   abandon → 0000, about → 0003, actual → 0015 → "000000030015"
   *
   * @param  {string} inputWords - Space-separated BIP39 mnemonic words (already normalised).
   * @returns {string} Concatenated zero-padded decimal index string.
   * @throws {Error} If any word is not in the BIP39 wordlist.
   */
  function wordsToIndices(inputWords) {
    const wordsArray = inputWords.trim().split(/\s+/);
    return wordsArray
      .map((word) => {
        const index = words.indexOf(word.toLowerCase());
        if (index === -1) throw new Error(`Word "${word}" not found`);
        return index.toString().padStart(4, '0');
      })
      .join('');
  }

  // ─────────────────────────────────────────────────────────────────────────
  // BIP39 seed phrase validation
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Cryptographically verify a BIP39 seed phrase including its checksum.
   *
   * BIP39 validation steps:
   *   1. Normalise whitespace and lowercase.
   *   2. Check word count is one of: 12, 15, 18, 21, 24.
   *      (Each encodes 11 bits: 12 words = 132 bits = 128 entropy + 4 checksum)
   *   3. Verify every word exists in the BIP39 wordlist.
   *   4. Reconstruct the full binary string (each word → 11-bit index).
   *   5. Split into entropy bits and checksum bits.
   *      - For N words: total = N * 11 bits; checksum = total / 32 bits
   *   6. Convert entropy bits to a byte array and SHA-256 hash it.
   *   7. Compare the first `checksumBits` of the hash to the recorded checksum.
   *
   * This validates not just that words are real BIP39 words, but that the
   * specific combination was generated by a correct BIP39 implementation.
   *
   * @async
   * @param  {string} seedPhrase - The raw seed phrase string entered by the user.
   * @returns {Promise<boolean>} true if the phrase is a valid BIP39 mnemonic.
   */
  async function verifyBip39SeedPhrase(seedPhrase) {
    const normalized = seedPhrase.replace(/\s+/g, ' ').trim().toLowerCase();
    const seedWords = normalized.split(' ');

    if (![12, 15, 18, 21, 24].includes(seedWords.length)) return false;

    const invalid = seedWords.filter((w) => !words.includes(w));
    if (invalid.length > 0) return false;

    // BIP39: total bits = wordCount * 11; checksum = totalBits / 32
    const totalBits = seedWords.length * 11;
    const checksumBits = totalBits % 32;
    const entropyBits = totalBits - checksumBits;

    // Reconstruct the full binary string from word indices
    const binary = seedWords
      .map((w) => words.indexOf(w).toString(2).padStart(11, '0'))
      .join('');
    const entropy = binary.slice(0, entropyBits);
    const checksum = binary.slice(entropyBits);

    // Convert entropy binary string → Uint8Array
    const entropyBytes = new Uint8Array(entropy.length / 8);
    for (let i = 0; i < entropy.length; i += 8) {
      entropyBytes[i / 8] = parseInt(entropy.slice(i, i + 8), 2);
    }

    // SHA-256 hash the entropy and compare the first `checksumBits` to stored checksum
    const hashBuffer = await crypto.subtle.digest('SHA-256', entropyBytes);
    const hashBinary = Array.from(new Uint8Array(hashBuffer))
      .map((b) => b.toString(2).padStart(8, '0'))
      .join('');

    return checksum === hashBinary.slice(0, checksumBits);
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Seed phrase generation
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Generate a new cryptographically random 12-word BIP39 mnemonic.
   *
   * Algorithm:
   *   1. Generate 16 bytes (128 bits) of entropy using `crypto.getRandomValues`.
   *   2. SHA-256 hash the entropy; take the first `entropyBits / 32` bits as checksum.
   *      For 128-bit entropy: checksum = 4 bits.
   *   3. Concatenate entropy bits + checksum bits → 132-bit string.
   *   4. Split into 12 × 11-bit groups; map each group to its BIP39 word.
   *
   * The resulting mnemonic is fully compatible with any standard BIP39 wallet
   * (MetaMask, hardware wallets, etc.).
   *
   * @async
   * @returns {Promise<string>} Space-separated 12-word BIP39 mnemonic.
   */
  async function generateMnemonic() {
    const entropy = new Uint8Array(16); // 128 bits
    crypto.getRandomValues(entropy);

    // Convert entropy bytes → binary string
    const entropyBinary = Array.from(entropy)
      .map((b) => b.toString(2).padStart(8, '0'))
      .join('');

    // Compute SHA-256 checksum
    const hashBuffer = await crypto.subtle.digest('SHA-256', entropy);
    const hashBinary = Array.from(new Uint8Array(hashBuffer))
      .map((b) => b.toString(2).padStart(8, '0'))
      .join('');

    // For 128-bit entropy, checksum length = 128 / 32 = 4 bits
    const checksumBits = entropyBinary.length / 32;

    // Full binary = entropy + first checksumBits of hash
    const fullBinary = entropyBinary + hashBinary.slice(0, checksumBits);

    // Split into 11-bit groups and map to words (128 + 4 bits = 132 bits = 12 words)
    const mnemonic = [];
    for (let i = 0; i < fullBinary.length; i += 11) {
      mnemonic.push(words[parseInt(fullBinary.slice(i, i + 11), 2)]);
    }

    return mnemonic.join(' ');
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Key derivation
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Derive the vault private key from a BIP39 seed phrase.
   *
   * This is NOT the standard BIP39/BIP32 HD wallet derivation (PBKDF2 + HMAC-SHA512).
   * It is Vault's own lightweight scheme:
   *   1. Map each word to its BIP39 wordlist index (0–2047).
   *   2. Concatenate the 4-digit decimal indices → one large decimal number string.
   *   3. Convert that decimal string to hexadecimal.
   *
   * The resulting hex string is the private key used in password generation.
   *
   * Compatibility note: this is identical to the web version's derivation,
   * so the same seed phrase produces the same passwords in both environments.
   *
   * @async
   * @param  {string} seedPhrase - The seed phrase (any whitespace, any case).
   * @returns {Promise<string>} Hexadecimal private key string.
   */
  async function derivePrivateKey(seedPhrase) {
    const normalized = seedPhrase.replace(/\s+/g, ' ').trim().toLowerCase();
    const indices = wordsToIndices(normalized);
    return decimalStringToHex(indices);
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Password generation
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Compute the SHA-256 hash of a string and return it as a lowercase hex string.
   *
   * Uses CryptoJS (synchronous) rather than the Web Crypto API to avoid async
   * in hot paths. CryptoJS is bundled as `lib/crypto-js.min.js`.
   *
   * @param  {string} text - Input text to hash.
   * @returns {string} 64-character lowercase hex SHA-256 digest.
   */
  function hash(text) {
    return CryptoJS.SHA256(text).toString();
  }

  /**
   * Generate the deterministic password for a site/user/nonce combination.
   *
   * Formula (compatible with the PasswordManagerWeb web version):
   *   ```
   *   entropy = SHA256( privateKey + "/" + user + "/" + site + "/" + nonce )
   *                .substring(0, hashLength)
   *   password = "PASS" + entropy + "249+"
   *   ```
   *
   * The `PASS` prefix and `249+` suffix ensure the password satisfies most
   * common password complexity requirements:
   *   - At least one uppercase letter (P, A, S)
   *   - At least one digit (2, 4, 9)
   *   - At least one special character (+)
   *   - Length ≥ 4 + hashLength + 4 (default: 24 characters)
   *
   * The nonce (version) allows generating a different password for the same
   * site/user without changing the seed phrase — useful when forced to reset.
   *
   * @param  {string} privateKey  - Hex private key derived from the seed phrase.
   * @param  {string} user        - Username or email address.
   * @param  {string} site        - Domain name (e.g., "github.com").
   * @param  {number} nonce       - Version counter (0-based; displayed as nonce+1 in UI).
   * @param  {number} [hashLength=16] - Number of hex characters to use from the SHA-256 output.
   * @returns {string} The generated password string.
   */
  function generatePassword(privateKey, user, site, nonce, hashLength = 16) {
    const concat = `${privateKey}/${user}/${site}/${nonce}`;
    const entropy = hash(concat).substring(0, hashLength);
    return 'PASS' + entropy + '249+';
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Domain utilities
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Extract the registrable domain (eTLD+1) from a full URL.
   *
   * Examples:
   *   "https://mail.google.com/inbox"  → "google.com"
   *   "https://www.bbc.co.uk/news"     → "bbc.co.uk"
   *   "https://github.com/"            → "github.com"
   *
   * Limitation: uses a static list of two-part TLDs rather than the Public
   * Suffix List (PSL). Unknown compound TLDs will be treated as single-part
   * (e.g., "foo.bar.unknown" → "bar.unknown").
   *
   * @param  {string} url - A full URL string (e.g., from `chrome.tabs`).
   * @returns {string} The registrable domain, or the original `url` on parse failure.
   */
  function extractDomain(url) {
    try {
      const hostname = new URL(url).hostname;
      // Simple: take last 2 parts (or 3 for co.uk etc.)
      const parts = hostname.split('.');
      if (parts.length <= 2) return hostname;
      // Handle common two-part TLDs
      const twoPartTLDs = ['co.uk', 'com.au', 'com.br', 'co.jp', 'co.kr', 'com.ar'];
      const lastTwo = parts.slice(-2).join('.');
      if (twoPartTLDs.includes(lastTwo)) {
        return parts.slice(-3).join('.');
      }
      return parts.slice(-2).join('.');
    } catch {
      return url;
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Password strength estimation
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Estimate the effective entropy and label for a password with the given hash length.
   *
   * Vault passwords consist of hex characters from a SHA-256 output.
   * Each hex character provides 4 bits of entropy (log₂(16) = 4).
   * The `PASS` prefix and `249+` suffix are constant and contribute 0 bits.
   *
   * Entropy tiers:
   *   - ≥ 80 bits (hashLength ≥ 20): "Excellent" — exceeds NIST 2023 recommendations
   *   - ≥ 64 bits (hashLength ≥ 16): "Strong"    — default setting
   *   - ≥ 48 bits (hashLength ≥ 12): "Good"      — acceptable for low-risk accounts
   *   - < 48 bits                  : "Weak"       — not recommended
   *
   * @param  {number} hashLength - Number of hex characters in the entropy portion.
   * @returns {{ bits: number, label: string, color: string, len: number }}
   *           bits  — entropy bits (hashLength * 4)
   *           label — human-readable strength label
   *           color — CSS colour string for the strength indicator
   *           len   — total password length (4 + hashLength + 4)
   */
  function getPasswordStrength(hashLength) {
    const hexBits = hashLength * 4;
    const totalLen = 4 + hashLength + 4;

    if (hexBits >= 80) return { bits: hexBits, label: 'Excellent', color: '#4ade80', len: totalLen };
    if (hexBits >= 64) return { bits: hexBits, label: 'Strong', color: '#4ade80', len: totalLen };
    if (hexBits >= 48) return { bits: hexBits, label: 'Good', color: '#f59e0b', len: totalLen };
    return { bits: hexBits, label: 'Weak', color: '#ff4d6a', len: totalLen };
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Nostr key derivation
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Derive a Nostr key pair from the vault private key.
   *
   * This is a one-way deterministic mapping:
   *   Nostr sk = SHA-256( UTF-8(vaultPrivateKey) ) as hex string
   *
   * The Nostr public key (`pk`) is derived from `sk` by `nostr-tools.getPublicKey`,
   * which performs secp256k1 scalar multiplication.
   *
   * NOTE: This function only returns the secret key (`sk`). The caller must use
   * `nostr-tools.getPublicKey(sk)` to obtain the public key. See `VaultStorage`
   * for the full pair derivation pattern.
   *
   * @async
   * @param  {string} privateKey - Vault hex private key.
   * @returns {Promise<{ sk: string }>} Object with the Nostr secret key (hex).
   */
  async function deriveNostrKeys(privateKey) {
    const utf8 = new TextEncoder().encode(privateKey);
    const hashBuffer = await crypto.subtle.digest('SHA-256', utf8);
    const sk = Array.from(new Uint8Array(hashBuffer))
      .map(b => b.toString(16).padStart(2, '0')).join('');
    return { sk };
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Public API
  // ─────────────────────────────────────────────────────────────────────────

  return {
    decimalStringToHex,
    wordsToIndices,
    verifyBip39SeedPhrase,
    generateMnemonic,
    derivePrivateKey,
    hash,
    generatePassword,
    extractDomain,
    getPasswordStrength,
    deriveNostrKeys,
  };
})();

// Node.js compatibility (for unit testing outside the browser)
if (typeof module !== 'undefined') module.exports = VaultCore;
